#!/bin/bash

BLUE="\033[1;34m"
CYAN="\033[1;36m"
GREEN="\033[1;32m"
NC="\033[0m"

echo -e "\nBASIC COMMAND IN CLI\n"
echo -e "${BLUE}export PATH${CYAN}=\"\$PATH:${GREEN}path to scripts directory${CYAN}\" ${NC}- Add path to scripts directory.\nExample: ${BLUE}export PATH${CYAN}=\"\$PATH:${GREEN}/home/sirmaxen/bin/scripts${CYAN}\"${NC}"
echo -e "Add above command to your shell configuration file located in your home ~ directory on the end of the file. \nFor ubuntu: ${BLUE}nano ~/.bashrc \n${NC}For MacOS: ${BLUE}nano ~/.zshrc"
echo ""
echo -e "${BLUE}man${CYAN} command ${NC}- Show manual for command"
echo ""
echo -e "${BLUE}pwd ${NC}- Prints the full name (the full path) of current/working directory"
echo ""
echo -e "${BLUE}ls ${NC}- List directory contents"
echo -e "${BLUE}ls ${GREEN}-a ${NC}- List all the content, including hidden files"
echo -e "${BLUE}ls ${GREEN}-l ${NC}- List the content and its information"
echo ""
echo -e "${BLUE}mkdir ${CYAN}foldername ${NC}– Create a new directory foldername"
echo ""
echo -e "${BLUE}cd ${CYAN}foldername ${NC}– Change the working directory to foldername"
echo -e "${BLUE}cd ${NC}- Return to $HOME directory"
echo -e "${BLUE}cd ${CYAN}.. ${NC}- Go up a directory"
echo -e "${BLUE}cd ${CYAN}- ${NC}- Return to the previous directory"
echo ""
echo -e "${BLUE}touch ${CYAN}file ${NC}- Create new file"
echo ""
echo -e "${BLUE}cp ${CYAN}source destination ${NC}– Copy source to destination"
echo -e "${BLUE}cp ${GREEN}-r ${CYAN}source destination ${NC}– Copy a directory recursively from source to destination"
echo ""
echo -e "${BLUE}mv ${CYAN}source destination ${NC}- Move (or rename) a file from source to destination"
echo ""
echo -e "${BLUE}nano ${NC}– File editor"
echo ""
echo -e "${BLUE}rm ${CYAN}file1 ${NC}- Remove file1"
echo -e "${BLUE}rm ${GREEN}-r ${CYAN}folder ${NC}- Remove a directory and its contents recursively"
echo ""
echo -e "${BLUE}cat ${CYAN}file ${NC}– Print contents of file on the screen"
echo -e "${BLUE}less ${CYAN}file ${NC}- View and paginate file"
echo -e "${BLUE}head ${CYAN}file ${NC}- Show first 10 lines of file"
echo -e "${BLUE}tail ${CYAN}file ${NC}- Show last 10 lines of file"
echo -e "${BLUE}chmod ${CYAN}file ${NC}- Show first 10 lines of file"
echo ""
echo -e "${BLUE}chmod ${GREEN}-R ${CYAN}u=rwx,g=,o=,a= directory${NC}- changes permissions (r-read, w-write, x-execute) for user, where u - user/owner, g - group, o - other, a - all"
echo -e "${BLUE}sudo chown ${CYAN}newowner file ${NC}- set owner of new file"
echo ""